### ISSUE TITLE
After installing the plugin almost all GUI labels show as "#PLG_STATISTICS..."

### ISSUE THREAD

**Issue by luebbe** [Fasse/admidio-statistics#6]
I guess the screenshot says it all:
![grafik](https://user-images.githubusercontent.com/3872576/141683858-1219fb5d-cb0e-43be-8a17-032f576f69c2.png)

The ballon help on the (i) buttons is wrong as well, but the text displayed after a click is ok.

Is ist a permission problem on the webserver?

**Comment by Fasse** [comment]
You should restart your browser. After that the labels should be shown correct.

With version 4.1 [this](https://github.com/Admidio/admidio/issues/1129) will fix the problem.

**Comment by luebbe** [comment]
Thank you, that improved the situation. There are however still two labels left:
![grafik](https://user-images.githubusercontent.com/3872576/141692549-cd2e15e5-5316-411f-961c-367c474c5ef4.png)
The first of these returns a valid error message and the second leads to a white page, probably error 500

**Comment by Fasse** [comment]
hmm, I could not reproduce that problem. Within my Installation I could view all translation strings.

**Comment by luebbe** [comment]
I double-checked by opening Admidio in a browser in which it was never opened before and the symptoms are the same.
The age statistic looks like this in the statistics editor:
![grafik](https://user-images.githubusercontent.com/3872576/141696973-629a9610-8522-4a91-a7cf-af47033f7aa1.png)

Is there something missing from the file system? I unpacked the statistics-3.1.3.zip file, which i downloaded from the admidio web site and uploaded everything apart from the .git folder into adm_plugins. After that I ran the install.php script.
BTW: Why does the zip file contain a .git folder? ;-)

**Comment by Fasse** [comment]
Which version of Admidio do you use? 4.0.11?

**Comment by luebbe** [comment]
Sorry It's Admidio 4.1. I thought I had mentioned it in the issue, because I had the same problem when I tried out Kategorierepot: https://github.com/rmbinder/Kategoriereport/issues/30. There I learned that Kategoriereport is incompatible with Admidio 4.1. Could this also be the case here?

**Comment by Fasse** [comment]
yes, the plugin from the homepage is incompatible. Only the last checkins of the plugin are compatible with admidio 4.1
