### ISSUE TITLE
Summary row shows pound sign instead of sum

### ISSUE THREAD

**Issue by luebbe** [Fasse/admidio-statistics#7]
Admidio 4.011 Statistics 3.1.3

I'm a bit confused that summary row in the age statistics shows a pound sign (£). I would have expected a Sigma (Σ) instead 
![grafik](https://user-images.githubusercontent.com/3872576/144714015-4791ed4c-23fb-4756-89ae-dae894aa127d.png)

**Comment by Fasse** [comment]
This was fixed with 5cca29fa8b2784b7f3de4995c397a289b6b24f73 and will be included in the next version.
