### ISSUE TITLE
Link to statistik editor in Admidio setup

### ISSUE THREAD

**Issue by bembi64** [Fasse/admidio-statistics#8]
Hello,
Admidio 4.1.7
Statistics 3.2.0

I had to change the menu item link for the statistik editor from
https://mydomain.tld.com/adm_plugins/statistics/gui/editor.php
to
https://mydomain.tld.com/adm_plugins/statistics/gui/editor.php?sta_id=0
to get it work.

The link without parameter results into 
ERR_TOO_MANY_REDIRECTS

as the url loops between
/adm_plugins/statistics/gui/editor_process.php?mode=load&scroll_pos=0
and
/adm_plugins/statistics/gui/editor.php?

**Comment by Fasse** [comment]
That problem should be fixed with the latest version of this plugin.
